################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../system/src/cmsis/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.c \
../system/src/cmsis/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.c \
../system/src/cmsis/FilteringFunctions/arm_biquad_cascade_df1_f32.c \
../system/src/cmsis/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.c \
../system/src/cmsis/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.c \
../system/src/cmsis/FilteringFunctions/arm_biquad_cascade_df1_init_f32.c \
../system/src/cmsis/FilteringFunctions/arm_biquad_cascade_df1_init_q15.c \
../system/src/cmsis/FilteringFunctions/arm_biquad_cascade_df1_init_q31.c \
../system/src/cmsis/FilteringFunctions/arm_biquad_cascade_df1_q15.c \
../system/src/cmsis/FilteringFunctions/arm_biquad_cascade_df1_q31.c \
../system/src/cmsis/FilteringFunctions/arm_biquad_cascade_df2T_f32.c \
../system/src/cmsis/FilteringFunctions/arm_biquad_cascade_df2T_f64.c \
../system/src/cmsis/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.c \
../system/src/cmsis/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.c \
../system/src/cmsis/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.c \
../system/src/cmsis/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.c \
../system/src/cmsis/FilteringFunctions/arm_conv_f32.c \
../system/src/cmsis/FilteringFunctions/arm_conv_fast_opt_q15.c \
../system/src/cmsis/FilteringFunctions/arm_conv_fast_q15.c \
../system/src/cmsis/FilteringFunctions/arm_conv_fast_q31.c \
../system/src/cmsis/FilteringFunctions/arm_conv_opt_q15.c \
../system/src/cmsis/FilteringFunctions/arm_conv_opt_q7.c \
../system/src/cmsis/FilteringFunctions/arm_conv_partial_f32.c \
../system/src/cmsis/FilteringFunctions/arm_conv_partial_fast_opt_q15.c \
../system/src/cmsis/FilteringFunctions/arm_conv_partial_fast_q15.c \
../system/src/cmsis/FilteringFunctions/arm_conv_partial_fast_q31.c \
../system/src/cmsis/FilteringFunctions/arm_conv_partial_opt_q15.c \
../system/src/cmsis/FilteringFunctions/arm_conv_partial_opt_q7.c \
../system/src/cmsis/FilteringFunctions/arm_conv_partial_q15.c \
../system/src/cmsis/FilteringFunctions/arm_conv_partial_q31.c \
../system/src/cmsis/FilteringFunctions/arm_conv_partial_q7.c \
../system/src/cmsis/FilteringFunctions/arm_conv_q15.c \
../system/src/cmsis/FilteringFunctions/arm_conv_q31.c \
../system/src/cmsis/FilteringFunctions/arm_conv_q7.c \
../system/src/cmsis/FilteringFunctions/arm_correlate_f32.c \
../system/src/cmsis/FilteringFunctions/arm_correlate_fast_opt_q15.c \
../system/src/cmsis/FilteringFunctions/arm_correlate_fast_q15.c \
../system/src/cmsis/FilteringFunctions/arm_correlate_fast_q31.c \
../system/src/cmsis/FilteringFunctions/arm_correlate_opt_q15.c \
../system/src/cmsis/FilteringFunctions/arm_correlate_opt_q7.c \
../system/src/cmsis/FilteringFunctions/arm_correlate_q15.c \
../system/src/cmsis/FilteringFunctions/arm_correlate_q31.c \
../system/src/cmsis/FilteringFunctions/arm_correlate_q7.c \
../system/src/cmsis/FilteringFunctions/arm_fir_decimate_f32.c \
../system/src/cmsis/FilteringFunctions/arm_fir_decimate_fast_q15.c \
../system/src/cmsis/FilteringFunctions/arm_fir_decimate_fast_q31.c \
../system/src/cmsis/FilteringFunctions/arm_fir_decimate_init_f32.c \
../system/src/cmsis/FilteringFunctions/arm_fir_decimate_init_q15.c \
../system/src/cmsis/FilteringFunctions/arm_fir_decimate_init_q31.c \
../system/src/cmsis/FilteringFunctions/arm_fir_decimate_q15.c \
../system/src/cmsis/FilteringFunctions/arm_fir_decimate_q31.c \
../system/src/cmsis/FilteringFunctions/arm_fir_f32.c \
../system/src/cmsis/FilteringFunctions/arm_fir_fast_q15.c \
../system/src/cmsis/FilteringFunctions/arm_fir_fast_q31.c \
../system/src/cmsis/FilteringFunctions/arm_fir_init_f32.c \
../system/src/cmsis/FilteringFunctions/arm_fir_init_q15.c \
../system/src/cmsis/FilteringFunctions/arm_fir_init_q31.c \
../system/src/cmsis/FilteringFunctions/arm_fir_init_q7.c \
../system/src/cmsis/FilteringFunctions/arm_fir_interpolate_f32.c \
../system/src/cmsis/FilteringFunctions/arm_fir_interpolate_init_f32.c \
../system/src/cmsis/FilteringFunctions/arm_fir_interpolate_init_q15.c \
../system/src/cmsis/FilteringFunctions/arm_fir_interpolate_init_q31.c \
../system/src/cmsis/FilteringFunctions/arm_fir_interpolate_q15.c \
../system/src/cmsis/FilteringFunctions/arm_fir_interpolate_q31.c \
../system/src/cmsis/FilteringFunctions/arm_fir_lattice_f32.c \
../system/src/cmsis/FilteringFunctions/arm_fir_lattice_init_f32.c \
../system/src/cmsis/FilteringFunctions/arm_fir_lattice_init_q15.c \
../system/src/cmsis/FilteringFunctions/arm_fir_lattice_init_q31.c \
../system/src/cmsis/FilteringFunctions/arm_fir_lattice_q15.c \
../system/src/cmsis/FilteringFunctions/arm_fir_lattice_q31.c \
../system/src/cmsis/FilteringFunctions/arm_fir_q15.c \
../system/src/cmsis/FilteringFunctions/arm_fir_q31.c \
../system/src/cmsis/FilteringFunctions/arm_fir_q7.c \
../system/src/cmsis/FilteringFunctions/arm_fir_sparse_f32.c \
../system/src/cmsis/FilteringFunctions/arm_fir_sparse_init_f32.c \
../system/src/cmsis/FilteringFunctions/arm_fir_sparse_init_q15.c \
../system/src/cmsis/FilteringFunctions/arm_fir_sparse_init_q31.c \
../system/src/cmsis/FilteringFunctions/arm_fir_sparse_init_q7.c \
../system/src/cmsis/FilteringFunctions/arm_fir_sparse_q15.c \
../system/src/cmsis/FilteringFunctions/arm_fir_sparse_q31.c \
../system/src/cmsis/FilteringFunctions/arm_fir_sparse_q7.c \
../system/src/cmsis/FilteringFunctions/arm_iir_lattice_f32.c \
../system/src/cmsis/FilteringFunctions/arm_iir_lattice_init_f32.c \
../system/src/cmsis/FilteringFunctions/arm_iir_lattice_init_q15.c \
../system/src/cmsis/FilteringFunctions/arm_iir_lattice_init_q31.c \
../system/src/cmsis/FilteringFunctions/arm_iir_lattice_q15.c \
../system/src/cmsis/FilteringFunctions/arm_iir_lattice_q31.c \
../system/src/cmsis/FilteringFunctions/arm_lms_f32.c \
../system/src/cmsis/FilteringFunctions/arm_lms_init_f32.c \
../system/src/cmsis/FilteringFunctions/arm_lms_init_q15.c \
../system/src/cmsis/FilteringFunctions/arm_lms_init_q31.c \
../system/src/cmsis/FilteringFunctions/arm_lms_norm_f32.c \
../system/src/cmsis/FilteringFunctions/arm_lms_norm_init_f32.c \
../system/src/cmsis/FilteringFunctions/arm_lms_norm_init_q15.c \
../system/src/cmsis/FilteringFunctions/arm_lms_norm_init_q31.c \
../system/src/cmsis/FilteringFunctions/arm_lms_norm_q15.c \
../system/src/cmsis/FilteringFunctions/arm_lms_norm_q31.c \
../system/src/cmsis/FilteringFunctions/arm_lms_q15.c \
../system/src/cmsis/FilteringFunctions/arm_lms_q31.c 

OBJS += \
./system/src/cmsis/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o \
./system/src/cmsis/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o \
./system/src/cmsis/FilteringFunctions/arm_biquad_cascade_df1_f32.o \
./system/src/cmsis/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o \
./system/src/cmsis/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o \
./system/src/cmsis/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o \
./system/src/cmsis/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o \
./system/src/cmsis/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o \
./system/src/cmsis/FilteringFunctions/arm_biquad_cascade_df1_q15.o \
./system/src/cmsis/FilteringFunctions/arm_biquad_cascade_df1_q31.o \
./system/src/cmsis/FilteringFunctions/arm_biquad_cascade_df2T_f32.o \
./system/src/cmsis/FilteringFunctions/arm_biquad_cascade_df2T_f64.o \
./system/src/cmsis/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o \
./system/src/cmsis/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o \
./system/src/cmsis/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o \
./system/src/cmsis/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o \
./system/src/cmsis/FilteringFunctions/arm_conv_f32.o \
./system/src/cmsis/FilteringFunctions/arm_conv_fast_opt_q15.o \
./system/src/cmsis/FilteringFunctions/arm_conv_fast_q15.o \
./system/src/cmsis/FilteringFunctions/arm_conv_fast_q31.o \
./system/src/cmsis/FilteringFunctions/arm_conv_opt_q15.o \
./system/src/cmsis/FilteringFunctions/arm_conv_opt_q7.o \
./system/src/cmsis/FilteringFunctions/arm_conv_partial_f32.o \
./system/src/cmsis/FilteringFunctions/arm_conv_partial_fast_opt_q15.o \
./system/src/cmsis/FilteringFunctions/arm_conv_partial_fast_q15.o \
./system/src/cmsis/FilteringFunctions/arm_conv_partial_fast_q31.o \
./system/src/cmsis/FilteringFunctions/arm_conv_partial_opt_q15.o \
./system/src/cmsis/FilteringFunctions/arm_conv_partial_opt_q7.o \
./system/src/cmsis/FilteringFunctions/arm_conv_partial_q15.o \
./system/src/cmsis/FilteringFunctions/arm_conv_partial_q31.o \
./system/src/cmsis/FilteringFunctions/arm_conv_partial_q7.o \
./system/src/cmsis/FilteringFunctions/arm_conv_q15.o \
./system/src/cmsis/FilteringFunctions/arm_conv_q31.o \
./system/src/cmsis/FilteringFunctions/arm_conv_q7.o \
./system/src/cmsis/FilteringFunctions/arm_correlate_f32.o \
./system/src/cmsis/FilteringFunctions/arm_correlate_fast_opt_q15.o \
./system/src/cmsis/FilteringFunctions/arm_correlate_fast_q15.o \
./system/src/cmsis/FilteringFunctions/arm_correlate_fast_q31.o \
./system/src/cmsis/FilteringFunctions/arm_correlate_opt_q15.o \
./system/src/cmsis/FilteringFunctions/arm_correlate_opt_q7.o \
./system/src/cmsis/FilteringFunctions/arm_correlate_q15.o \
./system/src/cmsis/FilteringFunctions/arm_correlate_q31.o \
./system/src/cmsis/FilteringFunctions/arm_correlate_q7.o \
./system/src/cmsis/FilteringFunctions/arm_fir_decimate_f32.o \
./system/src/cmsis/FilteringFunctions/arm_fir_decimate_fast_q15.o \
./system/src/cmsis/FilteringFunctions/arm_fir_decimate_fast_q31.o \
./system/src/cmsis/FilteringFunctions/arm_fir_decimate_init_f32.o \
./system/src/cmsis/FilteringFunctions/arm_fir_decimate_init_q15.o \
./system/src/cmsis/FilteringFunctions/arm_fir_decimate_init_q31.o \
./system/src/cmsis/FilteringFunctions/arm_fir_decimate_q15.o \
./system/src/cmsis/FilteringFunctions/arm_fir_decimate_q31.o \
./system/src/cmsis/FilteringFunctions/arm_fir_f32.o \
./system/src/cmsis/FilteringFunctions/arm_fir_fast_q15.o \
./system/src/cmsis/FilteringFunctions/arm_fir_fast_q31.o \
./system/src/cmsis/FilteringFunctions/arm_fir_init_f32.o \
./system/src/cmsis/FilteringFunctions/arm_fir_init_q15.o \
./system/src/cmsis/FilteringFunctions/arm_fir_init_q31.o \
./system/src/cmsis/FilteringFunctions/arm_fir_init_q7.o \
./system/src/cmsis/FilteringFunctions/arm_fir_interpolate_f32.o \
./system/src/cmsis/FilteringFunctions/arm_fir_interpolate_init_f32.o \
./system/src/cmsis/FilteringFunctions/arm_fir_interpolate_init_q15.o \
./system/src/cmsis/FilteringFunctions/arm_fir_interpolate_init_q31.o \
./system/src/cmsis/FilteringFunctions/arm_fir_interpolate_q15.o \
./system/src/cmsis/FilteringFunctions/arm_fir_interpolate_q31.o \
./system/src/cmsis/FilteringFunctions/arm_fir_lattice_f32.o \
./system/src/cmsis/FilteringFunctions/arm_fir_lattice_init_f32.o \
./system/src/cmsis/FilteringFunctions/arm_fir_lattice_init_q15.o \
./system/src/cmsis/FilteringFunctions/arm_fir_lattice_init_q31.o \
./system/src/cmsis/FilteringFunctions/arm_fir_lattice_q15.o \
./system/src/cmsis/FilteringFunctions/arm_fir_lattice_q31.o \
./system/src/cmsis/FilteringFunctions/arm_fir_q15.o \
./system/src/cmsis/FilteringFunctions/arm_fir_q31.o \
./system/src/cmsis/FilteringFunctions/arm_fir_q7.o \
./system/src/cmsis/FilteringFunctions/arm_fir_sparse_f32.o \
./system/src/cmsis/FilteringFunctions/arm_fir_sparse_init_f32.o \
./system/src/cmsis/FilteringFunctions/arm_fir_sparse_init_q15.o \
./system/src/cmsis/FilteringFunctions/arm_fir_sparse_init_q31.o \
./system/src/cmsis/FilteringFunctions/arm_fir_sparse_init_q7.o \
./system/src/cmsis/FilteringFunctions/arm_fir_sparse_q15.o \
./system/src/cmsis/FilteringFunctions/arm_fir_sparse_q31.o \
./system/src/cmsis/FilteringFunctions/arm_fir_sparse_q7.o \
./system/src/cmsis/FilteringFunctions/arm_iir_lattice_f32.o \
./system/src/cmsis/FilteringFunctions/arm_iir_lattice_init_f32.o \
./system/src/cmsis/FilteringFunctions/arm_iir_lattice_init_q15.o \
./system/src/cmsis/FilteringFunctions/arm_iir_lattice_init_q31.o \
./system/src/cmsis/FilteringFunctions/arm_iir_lattice_q15.o \
./system/src/cmsis/FilteringFunctions/arm_iir_lattice_q31.o \
./system/src/cmsis/FilteringFunctions/arm_lms_f32.o \
./system/src/cmsis/FilteringFunctions/arm_lms_init_f32.o \
./system/src/cmsis/FilteringFunctions/arm_lms_init_q15.o \
./system/src/cmsis/FilteringFunctions/arm_lms_init_q31.o \
./system/src/cmsis/FilteringFunctions/arm_lms_norm_f32.o \
./system/src/cmsis/FilteringFunctions/arm_lms_norm_init_f32.o \
./system/src/cmsis/FilteringFunctions/arm_lms_norm_init_q15.o \
./system/src/cmsis/FilteringFunctions/arm_lms_norm_init_q31.o \
./system/src/cmsis/FilteringFunctions/arm_lms_norm_q15.o \
./system/src/cmsis/FilteringFunctions/arm_lms_norm_q31.o \
./system/src/cmsis/FilteringFunctions/arm_lms_q15.o \
./system/src/cmsis/FilteringFunctions/arm_lms_q31.o 

C_DEPS += \
./system/src/cmsis/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d \
./system/src/cmsis/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d \
./system/src/cmsis/FilteringFunctions/arm_biquad_cascade_df1_f32.d \
./system/src/cmsis/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d \
./system/src/cmsis/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d \
./system/src/cmsis/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d \
./system/src/cmsis/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d \
./system/src/cmsis/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d \
./system/src/cmsis/FilteringFunctions/arm_biquad_cascade_df1_q15.d \
./system/src/cmsis/FilteringFunctions/arm_biquad_cascade_df1_q31.d \
./system/src/cmsis/FilteringFunctions/arm_biquad_cascade_df2T_f32.d \
./system/src/cmsis/FilteringFunctions/arm_biquad_cascade_df2T_f64.d \
./system/src/cmsis/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d \
./system/src/cmsis/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d \
./system/src/cmsis/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d \
./system/src/cmsis/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d \
./system/src/cmsis/FilteringFunctions/arm_conv_f32.d \
./system/src/cmsis/FilteringFunctions/arm_conv_fast_opt_q15.d \
./system/src/cmsis/FilteringFunctions/arm_conv_fast_q15.d \
./system/src/cmsis/FilteringFunctions/arm_conv_fast_q31.d \
./system/src/cmsis/FilteringFunctions/arm_conv_opt_q15.d \
./system/src/cmsis/FilteringFunctions/arm_conv_opt_q7.d \
./system/src/cmsis/FilteringFunctions/arm_conv_partial_f32.d \
./system/src/cmsis/FilteringFunctions/arm_conv_partial_fast_opt_q15.d \
./system/src/cmsis/FilteringFunctions/arm_conv_partial_fast_q15.d \
./system/src/cmsis/FilteringFunctions/arm_conv_partial_fast_q31.d \
./system/src/cmsis/FilteringFunctions/arm_conv_partial_opt_q15.d \
./system/src/cmsis/FilteringFunctions/arm_conv_partial_opt_q7.d \
./system/src/cmsis/FilteringFunctions/arm_conv_partial_q15.d \
./system/src/cmsis/FilteringFunctions/arm_conv_partial_q31.d \
./system/src/cmsis/FilteringFunctions/arm_conv_partial_q7.d \
./system/src/cmsis/FilteringFunctions/arm_conv_q15.d \
./system/src/cmsis/FilteringFunctions/arm_conv_q31.d \
./system/src/cmsis/FilteringFunctions/arm_conv_q7.d \
./system/src/cmsis/FilteringFunctions/arm_correlate_f32.d \
./system/src/cmsis/FilteringFunctions/arm_correlate_fast_opt_q15.d \
./system/src/cmsis/FilteringFunctions/arm_correlate_fast_q15.d \
./system/src/cmsis/FilteringFunctions/arm_correlate_fast_q31.d \
./system/src/cmsis/FilteringFunctions/arm_correlate_opt_q15.d \
./system/src/cmsis/FilteringFunctions/arm_correlate_opt_q7.d \
./system/src/cmsis/FilteringFunctions/arm_correlate_q15.d \
./system/src/cmsis/FilteringFunctions/arm_correlate_q31.d \
./system/src/cmsis/FilteringFunctions/arm_correlate_q7.d \
./system/src/cmsis/FilteringFunctions/arm_fir_decimate_f32.d \
./system/src/cmsis/FilteringFunctions/arm_fir_decimate_fast_q15.d \
./system/src/cmsis/FilteringFunctions/arm_fir_decimate_fast_q31.d \
./system/src/cmsis/FilteringFunctions/arm_fir_decimate_init_f32.d \
./system/src/cmsis/FilteringFunctions/arm_fir_decimate_init_q15.d \
./system/src/cmsis/FilteringFunctions/arm_fir_decimate_init_q31.d \
./system/src/cmsis/FilteringFunctions/arm_fir_decimate_q15.d \
./system/src/cmsis/FilteringFunctions/arm_fir_decimate_q31.d \
./system/src/cmsis/FilteringFunctions/arm_fir_f32.d \
./system/src/cmsis/FilteringFunctions/arm_fir_fast_q15.d \
./system/src/cmsis/FilteringFunctions/arm_fir_fast_q31.d \
./system/src/cmsis/FilteringFunctions/arm_fir_init_f32.d \
./system/src/cmsis/FilteringFunctions/arm_fir_init_q15.d \
./system/src/cmsis/FilteringFunctions/arm_fir_init_q31.d \
./system/src/cmsis/FilteringFunctions/arm_fir_init_q7.d \
./system/src/cmsis/FilteringFunctions/arm_fir_interpolate_f32.d \
./system/src/cmsis/FilteringFunctions/arm_fir_interpolate_init_f32.d \
./system/src/cmsis/FilteringFunctions/arm_fir_interpolate_init_q15.d \
./system/src/cmsis/FilteringFunctions/arm_fir_interpolate_init_q31.d \
./system/src/cmsis/FilteringFunctions/arm_fir_interpolate_q15.d \
./system/src/cmsis/FilteringFunctions/arm_fir_interpolate_q31.d \
./system/src/cmsis/FilteringFunctions/arm_fir_lattice_f32.d \
./system/src/cmsis/FilteringFunctions/arm_fir_lattice_init_f32.d \
./system/src/cmsis/FilteringFunctions/arm_fir_lattice_init_q15.d \
./system/src/cmsis/FilteringFunctions/arm_fir_lattice_init_q31.d \
./system/src/cmsis/FilteringFunctions/arm_fir_lattice_q15.d \
./system/src/cmsis/FilteringFunctions/arm_fir_lattice_q31.d \
./system/src/cmsis/FilteringFunctions/arm_fir_q15.d \
./system/src/cmsis/FilteringFunctions/arm_fir_q31.d \
./system/src/cmsis/FilteringFunctions/arm_fir_q7.d \
./system/src/cmsis/FilteringFunctions/arm_fir_sparse_f32.d \
./system/src/cmsis/FilteringFunctions/arm_fir_sparse_init_f32.d \
./system/src/cmsis/FilteringFunctions/arm_fir_sparse_init_q15.d \
./system/src/cmsis/FilteringFunctions/arm_fir_sparse_init_q31.d \
./system/src/cmsis/FilteringFunctions/arm_fir_sparse_init_q7.d \
./system/src/cmsis/FilteringFunctions/arm_fir_sparse_q15.d \
./system/src/cmsis/FilteringFunctions/arm_fir_sparse_q31.d \
./system/src/cmsis/FilteringFunctions/arm_fir_sparse_q7.d \
./system/src/cmsis/FilteringFunctions/arm_iir_lattice_f32.d \
./system/src/cmsis/FilteringFunctions/arm_iir_lattice_init_f32.d \
./system/src/cmsis/FilteringFunctions/arm_iir_lattice_init_q15.d \
./system/src/cmsis/FilteringFunctions/arm_iir_lattice_init_q31.d \
./system/src/cmsis/FilteringFunctions/arm_iir_lattice_q15.d \
./system/src/cmsis/FilteringFunctions/arm_iir_lattice_q31.d \
./system/src/cmsis/FilteringFunctions/arm_lms_f32.d \
./system/src/cmsis/FilteringFunctions/arm_lms_init_f32.d \
./system/src/cmsis/FilteringFunctions/arm_lms_init_q15.d \
./system/src/cmsis/FilteringFunctions/arm_lms_init_q31.d \
./system/src/cmsis/FilteringFunctions/arm_lms_norm_f32.d \
./system/src/cmsis/FilteringFunctions/arm_lms_norm_init_f32.d \
./system/src/cmsis/FilteringFunctions/arm_lms_norm_init_q15.d \
./system/src/cmsis/FilteringFunctions/arm_lms_norm_init_q31.d \
./system/src/cmsis/FilteringFunctions/arm_lms_norm_q15.d \
./system/src/cmsis/FilteringFunctions/arm_lms_norm_q31.d \
./system/src/cmsis/FilteringFunctions/arm_lms_q15.d \
./system/src/cmsis/FilteringFunctions/arm_lms_q31.d 


# Each subdirectory must supply rules for building sources it contributes
system/src/cmsis/FilteringFunctions/%.o: ../system/src/cmsis/FilteringFunctions/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM Cross C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m3 -mthumb -Og -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -ffreestanding -fno-move-loop-invariants -Wall -Wextra  -g3 -DDEBUG -DTRACE -I"../include" -I"../system/include" -I"../system/include/cmsis" -I"../system/include/ADuCM350" -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


