/*===================================================================
 Copyright (c), 2011 - Analog Devices Inc. All Rights Reserved.
This software is PROPRIETARY & CONFIDENTIAL to Analog Devices, Inc.
and its licensors.
====================================================================

 Automatically Generated File : version.h
 DO NOT EDIT
 (Any changes in here will be automatically overwritten!!)

 Generation Date:   YYYY-MM-DD HH:MM UTC
 Generated By:      <application name>
 Generator Version: <application version>

 Description:
   This file contain macro which defines the Build version 
   of OSAL for NON-OS system.
====================================================================*/


#ifndef __VERSION_H__
#define __VERSION_H__

/* This value is typically given on the compiler command-line */
#ifndef ADI_BUILD_VER
#define ADI_BUILD_VER 0u
#endif /* ADI_BUILD_VER */
#endif /* __VERSION_H__ */

/*
 EOF: version.h
*/
